# Built with Jekyll 3.2.0

# Setup
title:        'Teachings of Christ Mind'
tagline:      'A Guide For Living from the Mind of Christ'
description:  'A Library of Christ Mind Teachings.'
url:          'https://www.christmind.info'
baseurl:      ''
keywords:     'Christ Mind, ACIM, Way of Mastery, Raj, Jesus, Christ, Love'
home:         "/library/"
port:         4040

# About/contact
author:
  name:              Rick Mercer
  url:               https://twitter.com/rmercer33
  email:             rmercer33@gmail.com

# Permalinks
permalink: pretty
permalink: /:title/

# Set encoding to UTF-8
encoding: utf-8

# Collections for texts
collections:
  wom:
    output: true
    title: Way of Mastery
    url: /wom/intro/wom/
  nwffacim:
    output: true
    title: Northwest Foundation for ACIM
    url: /nwffacim/intro/nwffacim/
  acim:
    output: true
    title: A Course in Miracles
    url: /acim/intro/acim/

defaults:

# Way of Mastery
  - scope:
      path: ""
      type: wom
    values:
      layout: narrative
      source: Way of Mastery
      surl: /wom/intro/wom/
      sid: wom
      class: wom

# Way of the Heart
  - scope:
      path: "_wom/woh"
      type: wom
    values:
      bid: woh
      book: Way of the Heart
      burl: /wom/intro/woh/
      nav: nav/np-data.html
      contents: nav/contents.html

# Way of Transformation
  - scope:
      path: "_wom/wot"
      type: wom
    values:
      bid: wot
      book: Way of Transformation
      burl: /wom/intro/wot/
      nav: nav/np-data.html
      contents: nav/contents.html

# Way of Knowing
  - scope:
      path: "_wom/wok"
      type: wom
    values:
      bid: wok
      book: Way of Knowing
      burl: /wom/intro/wok/
      nav: nav/np-data.html
      contents: nav/contents.html

# Early years
  - scope:
      path: "_wom/early"
      type: wom
    values:
      bid: early
      complete: true
      book: The Early Years
      burl: /wom/intro/early/
      nav: nav/np-data.html
      contents: nav/contents.html

# The Jeshua Letters
  - scope:
      path: "_wom/tjl"
      type: wom
    values:
      bid: tjl
      complete: true
      book: The Jeshua Letters
      burl: /wom/intro/tjl/
      nav: nav/np-data.html
      contents: nav/contents.html
      class: "wom tjl"

# Way of the Servant
  - scope:
      path: "_wom/wos"
      type: wom
    values:
      bid: wos
      complete: true
      book: Way of the Servant
      burl: /wom/intro/wos/
      nav: nav/np-data.html
      contents: nav/contents.html
      class: "wom wos"

# WOM Q&A
  - scope:
      path: "_wom/questions"
      type: wom
    values:
      bid: questions
      complete: true
      book: Questions
      burl: /wom/intro/questions/
      nav: nav/np-data.html
      contents: nav/contents.html

# Paul Tuttle and Raj - Northwest Foundation for ACIM
  - scope:
      path: ""
      type: nwffacim
    values:
      layout: narrative
      source: Northwest Foundation for ACIM
      surl: /nwffacim/intro/nwffacim/
      sid: nwffacim
      class: nwffacim

# ACIM Study Group - many years of sessions
#  - scope:
#      path: ""
#      type: nwffacim
#    values:
#      bid: acimc
#      book: ACIM Study Group
#      burl: /nwffacim/intro/acim/
#      nav: nav/np-data.html
#      contents: nav/contents.html

# 2002
  - scope:
      path: "_nwffacim/2002"
      type: nwffacim
    values:
      bid: 2002
      unit: 2002 Contents
      uurl: /nwffacim/intro/2002/
      book: ACIM Study Group
      burl: /nwffacim/intro/acim/
      nav: nav/np-data.html

# 2003
  - scope:
      path: "_nwffacim/2003"
      type: nwffacim
    values:
      bid: 2003
      unit: 2003 Contents
      uurl: /nwffacim/intro/2003/
      book: ACIM Study Group
      burl: /nwffacim/intro/acim/
      nav: nav/np-data.html

# 2004
  - scope:
      path: "_nwffacim/2004"
      type: nwffacim
    values:
      bid: 2004
      unit: 2004 Contents
      uurl: /nwffacim/intro/2004/
      book: ACIM Study Group
      burl: /nwffacim/intro/acim/
      nav: nav/np-data.html

# 2005
  - scope:
      path: "_nwffacim/2005"
      type: nwffacim
    values:
      bid: 2005
      unit: 2005 Contents
      uurl: /nwffacim/intro/2005/
      book: ACIM Study Group
      burl: /nwffacim/intro/acim/
      nav: nav/np-data.html

# 2006
  - scope:
      path: "_nwffacim/2006"
      type: nwffacim
    values:
      bid: 2006
      unit: 2006 Contents
      uurl: /nwffacim/intro/2006/
      book: ACIM Study Group
      burl: /nwffacim/intro/acim/
      nav: nav/np-data.html

# 2007
  - scope:
      path: "_nwffacim/2007"
      type: nwffacim
    values:
      bid: 2007
      unit: 2007 Contents
      uurl: /nwffacim/intro/2007/
      book: ACIM Study Group
      burl: /nwffacim/intro/acim/
      nav: nav/np-data.html

# 2008
  - scope:
      path: "_nwffacim/2008"
      type: nwffacim
    values:
      bid: 2008
      unit: 2008 Contents
      uurl: /nwffacim/intro/2008/
      book: ACIM Study Group
      burl: /nwffacim/intro/acim/
      nav: nav/np-data.html

# 2009
  - scope:
      path: "_nwffacim/2009"
      type: nwffacim
    values:
      bid: 2009
      unit: 2009 Contents
      uurl: /nwffacim/intro/2009/
      book: ACIM Study Group
      burl: /nwffacim/intro/acim/
      nav: nav/np-data.html

# 2010
  - scope:
      path: "_nwffacim/2010"
      type: nwffacim
    values:
      bid: 2010
      unit: 2010 Contents
      uurl: /nwffacim/intro/2010/
      book: ACIM Study Group
      burl: /nwffacim/intro/acim/
      nav: nav/np-data.html

# 2011
  - scope:
      path: "_nwffacim/2011"
      type: nwffacim
    values:
      bid: 2011
      unit: 2011 Contents
      uurl: /nwffacim/intro/2011/
      book: ACIM Study Group
      burl: /nwffacim/intro/acim/
      nav: nav/np-data.html

# 2012
  - scope:
      path: "_nwffacim/2012"
      type: nwffacim
    values:
      bid: 2012
      unit: 2012 Contents
      uurl: /nwffacim/intro/2012/
      book: ACIM Study Group
      burl: /nwffacim/intro/acim/
      nav: nav/np-data.html

# 2013
  - scope:
      path: "_nwffacim/2013"
      type: nwffacim
    values:
      bid: 2013
      unit: 2013 Contents
      uurl: /nwffacim/intro/2013/
      book: ACIM Study Group
      burl: /nwffacim/intro/acim/
      nav: nav/np-data.html

# 2014
  - scope:
      path: "_nwffacim/2014"
      type: nwffacim
    values:
      bid: 2014
      unit: 2014 Contents
      uurl: /nwffacim/intro/2014/
      book: ACIM Study Group
      burl: /nwffacim/intro/acim/
      nav: nav/np-data.html

# 2015
  - scope:
      path: "_nwffacim/2015"
      type: nwffacim
    values:
      bid: 2015
      unit: 2015 Contents
      uurl: /nwffacim/intro/2015/
      book: ACIM Study Group
      burl: /nwffacim/intro/acim/
      nav: nav/np-data.html

# 2016
  - scope:
      path: "_nwffacim/2016"
      type: nwffacim
    values:
      bid: 2016
      unit: 2016 Contents
      uurl: /nwffacim/intro/2016/
      book: ACIM Study Group
      burl: /nwffacim/intro/acim/
      nav: nav/np-data.html

# 2017
  - scope:
      path: "_nwffacim/2017"
      type: nwffacim
    values:
      bid: 2017
      unit: 2017 Contents
      uurl: /nwffacim/intro/2017/
      book: ACIM Study Group
      burl: /nwffacim/intro/acim/
      nav: nav/np-data.html

# You Are the Answer ebook
  - scope:
      path: "_nwffacim/yaa"
      type: nwffacim
    values:
      bid: yaa
      book: You Are the Answer
      burl: /nwffacim/intro/yaa/
      contents: nav/contents.html
      nav: nav/np-data.html

# Graduation ebook
  - scope:
      path: "_nwffacim/grad"
      type: nwffacim
    values:
      bid: grad
      book: Graduation
      burl: /nwffacim/intro/grad/
      nav: nav/np-data.html
      contents: nav/contents.html

# ACIM Sparkly Edition
  - scope:
      path: ""
      type: acim
    values:
      layout: narrative
      source: A Course in Miracles
      surl: /acim/intro/acim/
      sid: acim
      class: acim

  - scope:
      path: "_acim/text"
      type: acim
    values:
      book: "ACIM Sparkly Edition: Text"
      burl: /acim/intro/text/
      nav: nav/np-data.html
      contents: nav/contents.html

  - scope:
      path: "_acim/manual"
      type: acim
    values:
      bid: manual
      book: "ACIM Sparkly Edition: Manual"
      burl: /acim/intro/manual/
      nav: nav/np-data.html
      contents: nav/contents.html

  - scope:
      path: "_acim/workbook"
      type: acim
    values:
      bid: workbook
      book: "ACIM Sparkly Edition: Workbook"
      burl: /acim/intro/workbook/
      nav: nav/np-data.html
      contents: nav/workbook.html
      xxcontents: nav/contents.html

  - scope:
      path: "_acim/text/01"
      type: acim
    values:
      bid: "atext01"
      burl: /acim/intro/text/#T1

  - scope:
      path: "_acim/text/02"
      type: acim
    values:
      bid: "atext02"
      burl: /acim/intro/text/#T2

  - scope:
      path: "_acim/text/03"
      type: acim
    values:
      bid: "atext03"
      burl: /acim/intro/text/#T3

  - scope:
      path: "_acim/text/04"
      type: acim
    values:
      bid: "atext04"
      burl: /acim/intro/text/#T4

  - scope:
      path: "_acim/text/05"
      type: acim
    values:
      bid: "atext05"
      burl: /acim/intro/text/#T5

  - scope:
      path: "_acim/text/06"
      type: acim
    values:
      bid: "atext06"
      burl: /acim/intro/text/#T6

  - scope:
      path: "_acim/text/07"
      type: acim
    values:
      bid: "atext07"
      burl: /acim/intro/text/#T7

  - scope:
      path: "_acim/text/08"
      type: acim
    values:
      bid: "atext08"
      burl: /acim/intro/text/#T8

  - scope:
      path: "_acim/text/09"
      type: acim
    values:
      bid: "atext09"
      burl: /acim/intro/text/#T9

  - scope:
      path: "_acim/text/10"
      type: acim
    values:
      bid: "atext10"
      burl: /acim/intro/text/#T10

  - scope:
      path: "_acim/text/11"
      type: acim
    values:
      bid: "atext11"
      burl: /acim/intro/text/#T11

  - scope:
      path: "_acim/text/12"
      type: acim
    values:
      bid: "atext12"
      burl: /acim/intro/text/#T12

  - scope:
      path: "_acim/text/13"
      type: acim
    values:
      bid: "atext13"
      burl: /acim/intro/text/#T13

  - scope:
      path: "_acim/text/14"
      type: acim
    values:
      bid: "atext14"
      burl: /acim/intro/text/#T14

  - scope:
      path: "_acim/text/15"
      type: acim
    values:
      bid: "atext15"
      burl: /acim/intro/text/#T15

  - scope:
      path: "_acim/text/16"
      type: acim
    values:
      bid: "atext16"
      burl: /acim/intro/text/#T16

  - scope:
      path: "_acim/text/17"
      type: acim
    values:
      bid: "atext17"
      burl: /acim/intro/text/#T17

  - scope:
      path: "_acim/text/18"
      type: acim
    values:
      bid: "atext18"
      burl: /acim/intro/text/#T18

  - scope:
      path: "_acim/text/19"
      type: acim
    values:
      bid: "atext19"
      burl: /acim/intro/text/#T19

  - scope:
      path: "_acim/text/20"
      type: acim
    values:
      bid: "atext20"
      burl: /acim/intro/text/#T20

  - scope:
      path: "_acim/text/21"
      type: acim
    values:
      bid: "atext21"
      burl: /acim/intro/text/#T21

  - scope:
      path: "_acim/text/22"
      type: acim
    values:
      bid: "atext22"
      burl: /acim/intro/text/#T22

  - scope:
      path: "_acim/text/23"
      type: acim
    values:
      bid: "atext23"
      burl: /acim/intro/text/#T23

  - scope:
      path: "_acim/text/24"
      type: acim
    values:
      bid: "atext24"
      burl: /acim/intro/text/#T24

  - scope:
      path: "_acim/text/25"
      type: acim
    values:
      bid: "atext25"
      burl: /acim/intro/text/#T25

  - scope:
      path: "_acim/text/26"
      type: acim
    values:
      bid: "atext26"
      burl: /acim/intro/text/#T26

  - scope:
      path: "_acim/text/27"
      type: acim
    values:
      bid: "atext27"
      burl: /acim/intro/text/#T27

  - scope:
      path: "_acim/text/28"
      type: acim
    values:
      bid: "atext28"
      burl: /acim/intro/text/#T28

  - scope:
      path: "_acim/text/29"
      type: acim
    values:
      bid: "atext29"
      burl: /acim/intro/text/#T29

  - scope:
      path: "_acim/text/30"
      type: acim
    values:
      bid: "atext30"
      burl: /acim/intro/text/#T30

  - scope:
      path: "_acim/text/31"
      type: acim
    values:
      bid: "atext31"
      burl: /acim/intro/text/#T31

# Markdown specs
markdown: kramdown

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  footnote_backlink: "&#x21a9;&#xfe0e;"
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Custom vars
version:             0.8.1
fb-appId:     448658485318107

# ----------- SINGLE PAGE TEMPLATE SUPPORT - USED FOR LANDING PAGE
### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#f8f8f8'
  blue:      '#49a7e9'
  green:     '#9bcf2f'
  purple:    '#c869bf'
  orange:    '#fab125'
  turquoise: '#0fbfcf'

# force inclusion of
include: [_redirects, LICENSE.txt]

# Exclusions from the final site
exclude: [
          _acim/text,
          _acim/manual,
          _acim/workbook,
          _wom/woh,
          _wom/wot,
          _wom/wok,
          _wom/early,
          _wom/tjl,
          _wom/wos,
          _wom/questions,
          _nwffacim/grad,
          _nwffacim/yaa,
          _nwffacim/2002,
          _nwffacim/2003,
          _nwffacim/2004,
          _nwffacim/2005,
          _nwffacim/2006,
          _nwffacim/2007,
          _nwffacim/2008,
          _nwffacim/2009,
          _nwffacim/2010,
          _nwffacim/2011,
          _nwffacim/2012,
          _nwffacim/2013,
          _nwffacim/2014,
          _nwffacim/2015,
          _nwffacim/2016,
  work, bin, src, config, optional, README.md, Gemfile, Gemfile.lock, Gruntfile.js, package.json, node_modules
]

keep_files: [
  acim,
  wom,
  nwffacim
]

