[[redirects]]
  from = "/wom/*"
  to = "https://www.christmind.info/t/wom/"
  status = 200

[[redirects]]
  from = "/nwffacim/*"
  to = "https://www.christmind.info/t/nwffacim/"
  status = 200

[[redirects]]
  from = "/acim/*"
  to = "https://www.christmind.info/t/acim/"
  status = 200

[[redirects]]
  from = "/"
  to = "https://www.christmind.info/"
  status = 200

[[redirects]]
  from = "/library/"
  to = "https://www.christmind.info/"
  status = 200

[[redirects]]
  from = "/library"
  to = "https://www.christmind.info/"
  status = 200

