#!/bin/bash

workingDir=`pwd`
scriptDir=`dirname $0`
scriptName=`basename $0`

womDir="/Users/rmercer/Projects/cmi/site/www/_wom"
womAwk="wom.awk"
nwffacimDir="/Users/rmercer/Projects/cmi/site/www/_nwffacim"
nwffacimAwk="nwffacim.awk"
unitDir=""
debug=0

function syntax {
  echo "prep -s <source> -b <book> file"
  echo " ex: prep -s nwffacim -b 2011 021911"
  exit 1
}

while getopts ds:b:y: args; do
    case $args in
        s) source=$OPTARG;;
        b) book=$OPTARG;;
        d) debug=1;;
        *) syntax;;
    esac
done

shift $(($OPTIND -1))

if [[ -z $1 ]]; then
  syntax
fi

unit=$1

case $source in
  wom)
    unitDir=$womDir
    awkFile=$womAwk
    ;;
  nwffacim)
    unitDir=$nwffacimDir
    awkFile=$nwffacimAwk
    ;;
  *) syntax;;
esac

unitDirName="${unitDir}/${book}"
unitFileName=${unitDirName}/${unit}.md

echo "Reading $unitFileName"

if [ $debug == 1 ]; then
  (gawk -f ${scriptDir}/${awkFile} -v debug=1 -v source=$source -v book=$book -v unit=$unit ${unitFileName} > $unit.json.debug)
else
  (gawk -f ${scriptDir}/${awkFile} -v debug=0 -v source=$source -v book=$book -v unit=$unit ${unitFileName} > $unit.json)
fi

rc="$?"

if [ "$rc" == "0" ]; then
  if [ $debug == 1 ]; then
    echo "./$unit.json.debug created."
  else
    echo "./$unit.json created."
  fi
else
  echo "conversion to json failed"
fi

